package com.demo.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="protab")

public class Product {
	@Id
	//to generate AutoGEnerated-Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
      private int proId;
	
	@Column(name="proName" , nullable=false ,unique=true)
      private String proName;
      private int qty;
	public Product() {
		super();
	}
	public Product( String proName, int qty) {
		super();
		
		this.proName = proName;
		this.qty = qty;
	}
	public int getProId() {
		return proId;
	}
	
	public String getProName() {
		return proName;
	}
	public void setProName(String proName) {
		this.proName = proName;
	}
	public int getQty() {
		return qty;
	}
	public void setQty(int qty) {
		this.qty = qty;
	}
	@Override
	public String toString() {
		return "Product [proId=" + proId + ", proName=" + proName + ", qty=" + qty + "]";
	}
      
      
}
